In [1]:
import torch

torch.manual_seed(1)

In [2]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [6]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])
print(M[0][1].item())

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
2.0
tensor([[1., 2.],
        [3., 4.]])


In [8]:
x = torch.randn((2, 2, 3))
print(x)

tensor([[[-0.8029,  0.2366,  0.2857],
         [ 0.6898, -0.6331,  0.8795]],

        [[-0.6842,  0.4533,  0.2912],
         [-0.8317, -0.5525,  0.6355]]])


In [9]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [10]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[-0.3968, -0.6571, -1.6428,  0.9803, -0.0421],
        [-0.8206,  0.3133, -1.1352,  0.3773, -0.2824],
        [-2.5667, -1.4303,  0.5009,  0.5438, -0.4057],
        [ 1.1341, -1.1115,  0.3501, -0.7703, -0.1473],
        [ 0.6272,  1.0935,  0.0939,  1.2381, -1.3459]])
tensor([[ 0.5119, -0.6933, -0.1668,  0.0554,  1.1340, -0.5326,  0.6592, -1.5964],
        [-0.9999, -1.6476,  0.8098, -0.3769, -3.1020, -0.0995, -0.7213,  1.2708]])
